name: Build and Deploy Chrome Extension

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the environment and inject the GitHub Secrets into the background script
      - name: Replace clipai API key in background script
        run: |
          # Replace the placeholder in background.js with the GitHub secret "clipai"
          sed -i "s|const API_KEY1 = \"API_KEY\";|const API_KEY1 = \"${{ secrets.clipai }}\";|" background.js

      # Step 3: (Optional) Build the extension (if you need a build step)
      - name: Build the Chrome Extension (optional)
        run: |
          # Example: Add build steps if needed (e.g., compiling TypeScript or minifying files)
          echo "Building extension..."

      # Step 4: (Optional) Package the extension
      - name: Package the extension
        run: |
          # Example: Package the extension into a .zip file for distribution
          zip -r extension.zip ./

      # Step 5: Deploy to Chrome Web Store or another platform (if needed)
      - name: Deploy extension (optional)
        run: |
          # Example: Add deployment step (e.g., using the Chrome Web Store API)
          echo "Deploying extension..."
